version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qrdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/migration.sql:/docker-entrypoint-initdb.d/migration.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db

  # frontend:
  #   build: ./frontend
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  db_data:
