basePath: /api/v1
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  qr-service_internal_model.Amount:
    properties:
      currency:
        type: string
      value:
        type: string
    required:
    - currency
    - value
    type: object
  qr-service_internal_model.GenerateQRRequest:
    properties:
      amount:
        $ref: '#/definitions/qr-service_internal_model.Amount'
      merchantId:
        type: string
      partnerReferenceNo:
        type: string
    required:
    - amount
    - merchantId
    - partnerReferenceNo
    type: object
  qr-service_internal_model.GenerateQRResponse:
    properties:
      partnerReferenceNo:
        type: string
      qrContent:
        type: string
      referenceNo:
        type: string
      responseCode:
        type: string
      responseMessage:
        type: string
    type: object
  qr-service_internal_model.PaymentCallbackRequest:
    properties:
      amount:
        allOf:
        - $ref: '#/definitions/qr-service_internal_model.Amount'
        description: '{value: "10000.00", currency: "IDR"}'
      originalPartnerReferenceNo:
        description: PartnerReferenceNo (DIRECT-API-NMS-whhq7gvx58)
        type: string
      originalReferenceNo:
        description: ReferenceNo internal (A0000000577)
        type: string
      paidTime:
        description: "2025-09-21T09:25:00+07:00"
        type: string
      transactionStatusDesc:
        description: Success, Failed, dll
        type: string
    required:
    - amount
    - originalPartnerReferenceNo
    - originalReferenceNo
    - paidTime
    - transactionStatusDesc
    type: object
  qr-service_internal_model.PaymentCallbackResponse:
    properties:
      responseCode:
        description: "2005100"
        type: string
      responseMessage:
        description: Successful
        type: string
      transactionStatusDesc:
        description: Success
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: manjo@example.com
    name: Manjo Developer
  description: Dokumentasi API untuk layanan QR Generator dan Callback.
  title: QR Payment API
  version: "1.0"
paths:
  /qr/generate:
    post:
      consumes:
      - application/json
      description: Endpoint untuk menghasilkan QR code baru dan menyimpan transaksi
        ke database dengan status PENDING.
      parameters:
      - description: HMAC-SHA256 Signature (Body Hash)
        in: header
        name: X-Signature
        required: true
        type: string
      - description: Data Transaksi yang dibutuhkan
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/qr-service_internal_model.GenerateQRRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qr-service_internal_model.GenerateQRResponse'
        "400":
          description: Validasi input gagal (misalnya Amount <= 0 atau field kosong)
          schema:
            $ref: '#/definitions/fiber.Map'
        "401":
          description: Signature Hash tidak valid (Unauthorized)
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Gagal menyimpan data transaksi ke database
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Generate QR Code
      tags:
      - QR
  /qr/payment:
    post:
      consumes:
      - application/json
      description: Endpoint callback dari payment gateway untuk mengupdate status
        transaksi.
      parameters:
      - description: HMAC-SHA256 Signature (Body Hash)
        in: header
        name: X-Signature
        required: true
        type: string
      - description: Data Callback Payment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/qr-service_internal_model.PaymentCallbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qr-service_internal_model.PaymentCallbackResponse'
        "400":
          description: Input validasi gagal atau data mismatch
          schema:
            $ref: '#/definitions/fiber.Map'
        "401":
          description: Signature Hash tidak valid
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Reference Number tidak ditemukan
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Gagal mengupdate status transaksi
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Process Payment Callback
      tags:
      - QR
swagger: "2.0"
